common:
  name: Common features
  desc: Not a page, just a list of common bits.
  do:
    - login
    - logout
  go: 
    - main
main:
  name: Main Page
  desc: The main page of the application. Yay!
  go:
    - list
list:
  name: A Listing
  desc: The listing of things in the application.
  go:
    - details
