version: "3"
services:
  api:
    container_name: "doggo-api"
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
